# Generated by Django 2.0.5 on 2018-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20181224_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examlog',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='examlog',
            name='weightage',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='question',
            name='weightage',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
